"""
Database models for ShapeX Studio MVP
"""
from sqlalchemy import Column, Integer, String, Float, DateTime, Text, Boolean, JSON, ForeignKey
from datetime import datetime
from app.models.database import Base


class StudioSession(Base):
    """Workflow execution tracking for Studio sessions"""
    __tablename__ = "studio_sessions"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(64), unique=True, nullable=False, index=True)
    idea_id = Column(Integer, ForeignKey('ideas.id'), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=True)

    # Session status
    status = Column(String(50), default="pending")  # pending, running, completed, failed
    progress = Column(Float, default=0.0)  # 0.0 to 1.0

    # Agent execution tracking
    agents_completed = Column(JSON)  # List of completed agent types
    current_agent = Column(String(50))  # Currently executing agent

    # Results
    blueprint_id = Column(Integer, nullable=True)

    # Performance metrics
    total_cost_usd = Column(Float, default=0.0)
    total_tokens_used = Column(Integer, default=0)
    duration_seconds = Column(Float)

    # Error handling
    error_message = Column(Text)
    retry_count = Column(Integer, default=0)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class AgentExecution(Base):
    """Individual agent execution tracking"""
    __tablename__ = "agent_executions"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(64), ForeignKey('studio_sessions.session_id'), nullable=False, index=True)
    agent_type = Column(String(50), nullable=False)  # researcher, validator, strategist

    # Execution status
    status = Column(String(50), default="pending")  # pending, running, completed, failed
    attempt_number = Column(Integer, default=1)

    # Input/Output
    input_context = Column(JSON)  # Context from previous agents
    raw_output = Column(Text)
    structured_output = Column(JSON)

    # Performance metrics
    tokens_used = Column(Integer)
    cost_usd = Column(Float)
    duration_seconds = Column(Float)

    # Model details
    model_name = Column(String(100), default="claude-sonnet-4-5")
    temperature = Column(Float, default=0.7)

    # Error handling
    error_message = Column(Text)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime)
    completed_at = Column(DateTime)


class Blueprint(Base):
    """Business blueprint generated by Studio agents"""
    __tablename__ = "blueprints"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(64), ForeignKey('studio_sessions.session_id'), unique=True, nullable=False)
    idea_id = Column(Integer, ForeignKey('ideas.id'), nullable=False)

    # MVP Sections (Only 3 for MVP)
    market_research = Column(JSON)       # ✅ From Researcher
    validation_report = Column(JSON)     # ✅ From Validator
    business_strategy = Column(JSON)     # ✅ From Strategist

    # Future Sections (Null for MVP)
    technical_architecture = Column(JSON)  # ⏳ Future: Architect
    design_specs = Column(JSON)            # ⏳ Future: Designer
    implementation_roadmap = Column(JSON)  # ⏳ Future: Builder

    # MVP Summary
    executive_summary = Column(Text)
    key_insights = Column(JSON)
    success_probability = Column(Float)  # 0-100

    # Export formats
    pdf_url = Column(String(500))
    json_export = Column(JSON)

    # Metadata
    version = Column(Integer, default=1)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class AgentContext(Base):
    """Context snapshots for agent execution"""
    __tablename__ = "agent_contexts"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String(64), ForeignKey('studio_sessions.session_id'), nullable=False, index=True)
    agent_type = Column(String(50), nullable=False)

    # Context data
    idea_snapshot = Column(JSON)  # Snapshot of idea at execution time
    previous_outputs = Column(JSON)  # Outputs from previous agents
    system_prompt = Column(Text)
    user_prompt = Column(Text)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)


class StudioAnalytics(Base):
    """Aggregate analytics for Studio usage"""
    __tablename__ = "studio_analytics"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, nullable=False, index=True)

    # Session metrics
    total_sessions = Column(Integer, default=0)
    completed_sessions = Column(Integer, default=0)
    failed_sessions = Column(Integer, default=0)
    success_rate = Column(Float, default=0.0)

    # Performance metrics
    avg_duration_seconds = Column(Float)
    avg_cost_usd = Column(Float)
    avg_tokens_used = Column(Integer)

    # Agent metrics
    researcher_executions = Column(Integer, default=0)
    validator_executions = Column(Integer, default=0)
    strategist_executions = Column(Integer, default=0)

    # Quality metrics
    avg_success_probability = Column(Float)
    blueprints_exported = Column(Integer, default=0)

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
